# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Martin Soko
title: Senior Computer Engineer/System administrator
email: sokomartinh@gmail.com
website: www.github.com/sokomartin

# Social links
# twitter_username: facespics
github_username:  sokomartin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sokomartin
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Martin and I'm a Computer Engineer/System administrator<mark>OSI</mark>. I'm a doer. Pragmatic <mark>Agile</mark>. I have worked at a number of companies gaining teamwork <mark>scrum</mark> and leadership skills.

  I am skilled in: <mark>Linux</mark> and <mark>C#.Net</mark> and <mark>OOP</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Science History
   - Karate
   - Running

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
